# Generated by Django 5.2.5 on 2025-08-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
